version: "3.8"
services:
  cimo_ms_automate_test:
    container_name: cimo-ms-automate-test
    build:
      context: ./
      dockerfile: ./docker/${DOCKERFILE}
      args:
        _ENV_NAME: ${ENV_NAME}
        _DOMAIN: ${DOMAIN}
        _TIMEZONE: ${MS_AT_TIMEZONE}
        _EXPOSE_PORT: ${MS_AT_SERVER_PORT}
        _PROXY_HTTP: ${MS_AT_PROXY_HTTP}
        _PROXY_HTTPS: ${MS_AT_PROXY_HTTPS}
        _PROXY_CERTIFICATE: ${MS_AT_PROXY_CERTIFICATE}
    env_file:
      - ./env/local.env
    ports:
      - 127.0.0.1:${MS_AT_SERVER_PORT}:${MS_AT_SERVER_PORT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/home/root/
      - ms_cronjob-volume:/home/root/certificate/
volumes:
  ms_cronjob-volume:
