version: "3.8"
services:
  cimo_ms_automate_test:
    container_name: cimo-ms-automate-test
    build:
      context: ./
      dockerfile: ./docker/${DOCKERFILE}
      args:
        _ENV_NAME: ${ENV_NAME}
        _DOMAIN: ${DOMAIN}
        _TIMEZONE: ${TIMEZONE}
        _SERVER_PORT: ${SERVER_PORT}
    env_file:
      - ./env/local.env
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/home/root/
      - ms_cronjob-volume:/home/root/.ms_cronjob-volume/:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
volumes:
  ms_cronjob-volume:
